# yaml-language-server: $schema=https://www.schemastore.org/any.json

run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - exhaustive
    - sqlclosecheck
    - rowserrcheck
    - bodyclose
    - errorlint
    - noctx
    - nilerr
    - unparam

linters-settings:
  exhaustive:
    default-signifies-exhaustive: true
